### ISSUE TITLE
Input should support TextArea type

### ISSUE THREAD

**Issue by carlito-scality** [scality/core-ui#113]
**Component**:Input

**Why this is needed**:
- this component currently supports `<input>` whose types are `text` and  `checkbox`. It should support `TextArea` type as well like below:

![image](https://user-images.githubusercontent.com/47394132/68505031-9fd9eb00-0266-11ea-9836-1d52c2c8c1f7.png)

**What should be done**:

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by felipebrunetti94** [comment]
You want a text, but different from this one ?
![image](https://user-images.githubusercontent.com/47053687/68500824-65a72400-023b-11ea-961d-4b7056e2d771.png)

**Comment by carlito-scality** [comment]
> You want a text, but different from this one ?
> ![image](https://user-images.githubusercontent.com/47053687/68500824-65a72400-023b-11ea-961d-4b7056e2d771.png)

@felipebrunetti94 I just updated the description. We would like this component to be able to display with a <TextArea> with label. Indeed, `Input` component is especially used in `<form>`.
![image](https://user-images.githubusercontent.com/47394132/68505408-69e93680-0267-11ea-98ac-217f8c7fe63f.png)

**Comment by felipebrunetti94** [comment]
Cool, now it is much better kkk, doing it right now.
