### ISSUE TITLE
ProgressBar

### ISSUE THREAD

**Issue by carlito-scality** [scality/core-ui#114]
**Component**: Progress Bar

**Why this is needed**:

**What should be done**:
![image](https://user-images.githubusercontent.com/47394132/67968087-0b88dc00-fc07-11e9-843d-c6856813f43a.png)

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by edumoreira1506** [comment]
Working in this issue!

**Comment by carlito-scality** [comment]
> Working in this issue!

@edumoreira1506 Nice!  Could you tackle the « blue » one with 4 labels on each corner for 1st PR? It should be in SVG 😉
