### ISSUE TITLE
Circular ProgressBar

### ISSUE THREAD

**Issue by carlito-scality** [scality/core-ui#115]
**Component**:Circular ProgressBar

**Why this is needed**:

**What should be done**:
![image](https://user-images.githubusercontent.com/47394132/67967223-8650f780-fc05-11e9-8930-6ac12fd1be16.png)

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by felipebrunetti94** [comment]
may I try, my good sir ?

**Comment by carlito-scality** [comment]
> may I try, my good sir ?

Sure! Thanks
By the way, it should be in SVG 😉
