### ISSUE TITLE
Navbar: Improvements

### ISSUE THREAD

**Issue by carlito-scality** [scality/core-ui#116]
**Component**: Navbar

**Why this is needed**:

**What should be done**:

Actual Navbar:
![image](https://user-images.githubusercontent.com/47394132/68209176-15c62400-ffd3-11e9-8005-514162d8be3a.png)

Use case to be covered:
![image](https://user-images.githubusercontent.com/47394132/67968310-6de1dc80-fc07-11e9-902e-f1c75b75325c.png)

Expected Navbar:
![navbar](https://user-images.githubusercontent.com/47394132/68212519-f7175b80-ffd9-11e9-8ba3-d9c281270829.png)

**Implementation proposal** (strongly recommended):
```
- Add `tabs` in the center of the Navbar.  Navbar inputs would be:

type Tab = {
  title: string,
  selected?: boolean,
  onClick: any => void
};

export type Props = {
  onToggleClick?: () => void,
  toggleVisible?: boolean,
  productName?: string,
  applications?: Items,
  help?: Items,
  user?: User,
  logo?: Node,
  languages?: Items,
  tabs?:Tab,
};

```
**Test plan**:

**Comment by felipebrunetti94** [comment]
May I help?

**Comment by felipebrunetti94** [comment]
Sorry but I'm having trouble with the setup, could you help me ?

**Comment by carlito-scality** [comment]
> May I help?

Hello! it would be nice 😊 We are working on a  new design about this component. We will update this issues next week with more details then we can tackle it.

**Comment by carlito-scality** [comment]
> Sorry but I'm having trouble with the setup, could you help me ?

Could you tell us more about your issue? You may find some help here https://github.com/scality/core-ui/blob/development/1.0/README.md#how-to-use-it

**Comment by carlito-scality** [comment]
@felipebrunetti94 FYI, I just updated the description of the issue :)

**Comment by felipebrunetti94** [comment]
Got it :D

**Comment by felipebrunetti94** [comment]
One question, this tabs, what exactly you want them to do ? Or I just make a template of a tab where you can insert a function or a link and name.
Just to be sure.

**Comment by carlito-scality** [comment]
> One question, this tabs, what exactly you want them to do ? Or I just make a template of a tab where you can insert a function or a link and name.
> Just to be sure.
 
This "tabs" should look like this the Tabs component we have (https://github.com/scality/core-ui/tree/development/1.0/src/lib/components/tabs) It would be great to refactor this component and use it in the Navbar. So a tab should be represented by:
```
type Tab = {
  title: string,
  selected?: boolean,
  onClick: any => void
};
```
Hopefully, it is clearer.

**Comment by felipebrunetti94** [comment]
Very helpful, thank you friend

**Comment by carlito-scality** [comment]
> Very helpful, thank you friend

IMO for the first PR, do not refactor the Tab component and just implement something similar that works in the Navbar and we can refactor later in another PR.

**Comment by felipebrunetti94** [comment]
:D nice 

> > Very helpful, thank you friend
> 
> IMO for the first PR, do not refactor the Tab component and just implement something similar that works in the Navbar and we can refactor later in another PR.

**Comment by felipebrunetti94** [comment]
Hey @carlito-scality  I've just open PR. If everything is okay, I can refact the <Tab /> component and use it in the <Navbar />.
How it sounds ?
