### ISSUE TITLE
Multi-Select List

### ISSUE THREAD

**Issue by carlito-scality** [scality/core-ui#12]
https://github.com/scality/pensieve-front/blob/master/src/react/ui-elements/MultipleSelect.jsx

State 1
<img width="472" alt="Screen Shot 2019-04-18 at 2 28 04 PM" src="https://user-images.githubusercontent.com/7453636/56392439-446edf80-61e6-11e9-8bdb-6f3cf7ca22b9.png">

State 2
<img width="463" alt="Screen Shot 2019-04-18 at 2 27 33 PM" src="https://user-images.githubusercontent.com/7453636/56392440-446edf80-61e6-11e9-9a23-c08a283547fa.png">

State 3
<img width="480" alt="Screen Shot 2019-04-18 at 2 27 21 PM" src="https://user-images.githubusercontent.com/7453636/56392441-446edf80-61e6-11e9-8741-4fc709a94a4b.png">

------------------------------
New Design:

![image](https://user-images.githubusercontent.com/47394132/66665744-728e2300-ec4f-11e9-9992-30f4bcba369e.png)

![image](https://user-images.githubusercontent.com/47394132/66665767-7f127b80-ec4f-11e9-8909-0da3f2221b42.png)

**Comment by edumoreira1506** [comment]
I am working in this issue!

**Comment by MonPote** [comment]
> I am working in this issue!

Hi @edumoreira1506 can you name your branch `feature/<the-name-of-your-branch>`, otherwise it won't trigger our bot and we won't be able to merge it.
