### ISSUE TITLE
Install core-ui dependency with yarn

### ISSUE THREAD

**Issue by nicolas2bert** [scality/core-ui#123]
**Component**:

Install

**What happened**:

Unable to use `scality/core-ui` installed as a dependency with yarm

**What was expected**:

**Steps to reproduce**

- Create a react project
- Add @scality/core-ui in the package.json's dependencies
- `yarn install`
- ```import { Button } from 'core-ui';```

Lifecycle scripts (e.g. prepare here:https://github.com/scality/core-ui/blob/development/1.0/package.json#L14) for hosted git dependencies don't run on install.
On install, `prepare` script does run,  `core-ui` code never gets transpiled into its `dist` directory and `core-ui` dependency is not accessible.

**Comment by carlito-scality** [comment]
- This is a choice we made to manage the installation See https://github.com/scality/core-ui/issues/68
- Ideally, we should publish the `dist` to npm so target projects can install core-ui via npm instead of git but it is not considered for now

**Comment by nicolas2bert** [comment]
I see, just want to warn you that installing `scality/core-ui` as a dependency with `yarn` does not seem to work. :)
