### ISSUE TITLE
Utils: improve mergeTheme

### ISSUE THREAD

**Issue by carlito-scality** [scality/core-ui#128]
**Component**:Utils

**Why this is needed**:

- We currently use `mergeTheme(props.theme, defaultTheme)` everywhere to merge theme from styled-component `ThemeProvider` (https://www.styled-components.com/docs/advanced) with our predefined core-ui's theme. It is very verbose. We could export it to `./utils` like this:

```
in ./utils:
const getTheme = (props) => mergeTheme(props.theme, defaultTheme);

in a component:

import { getTheme } from "../../utils";
const Items = styled.div`
${props => {
    const { primary } = getTheme(props);
     return css `color: ${primary}`;
}};
`;

```
**What should be done**:

- Apply changes in all components.

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by rubynho** [comment]
Hey @carlito-scality, I'd like to work on this enhancement!
