### ISSUE TITLE
Warning page

### ISSUE THREAD

**Issue by nicolas2bert** [scality/core-ui#15]
https://github.com/scality/pensieve-front/blob/master/src/react/ui-elements/Warning.jsx

<img width="448" alt="Screen Shot 2019-04-18 at 2 59 22 PM" src="https://user-images.githubusercontent.com/7453636/56393955-b47f6480-61ea-11e9-80fa-2a0299bee124.png">

**Comment by carlito-scality** [comment]
It could be implemented by using the Modal https://github.com/scality/core-ui/tree/development/1.0/src/lib/components/modal
