### ISSUE TITLE
<CollapsiblePanel> never gets exported

### ISSUE THREAD

**Issue by nicolas2bert** [scality/core-ui#171]
**Component**:

\<CollapsiblePanel\>

**What happened**:

Try to import \<CollapsiblePanel\> component to my project.

**Comment by ChengYanJin** [comment]
Thanks for reporting this bug!
I am sure you will fix it !!! And don't hesitate to make the changes to meet your specific requirements ;)

**Comment by ChengYanJin** [comment]
merged!
