### ISSUE TITLE
Tooltip display bug inside the Table Component 

### ISSUE THREAD

**Issue by ChengYanJin** [scality/core-ui#176]
**Component**:  Table

**What happened**:
When we have tooltip display inside the table, we cannot see the overlay.
We need to manually set 
```
  /* solve the tooltip display issue */
  .sc-table-column-cell-action {
    overflow: visible !important;
  }
```
**What was expected**:

**Steps to reproduce**

**Resolution proposal** (optional):

**Comment by gdemonet** [comment]
I'm not sure how this tooltip is supposed to work, but when objects more complex than a `String` appear in a table cell, the tooltip displays `object.Object`. Maybe that's also a bug, maybe it warrants a new ticket, I'll let you decide :)

**Comment by thomasdanan** [comment]
not relevant anymore
