### ISSUE TITLE
Configurable font family and sizes

### ISSUE THREAD

**Issue by nicolas2bert** [scality/core-ui#177]
- Define default font family and sizes

Default Font-family `Lato`, we should define the default fontFace in the theme.
```
export const fontFace = "Lato";
```

In the projects who use core-ui, download the font from Lato official website and define the css font-face (`woff` and `woff2` format).(http://www.latofonts.com/)
```
@font-face {
  font-family: 'Lato';
  font-style: normal;
  font-weight: normal;
  src: local(''),
       url('/brand/assets/fonts/lato/Lato-Regular.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
       url('/brand/assets/fonts/lato/Lato-Regular.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}
```

- Having them configurable.

**Comment by ChengYanJin** [comment]
There is no much value we predefine the font-family in core-ui. 
Because anyway we should set it in the micro-apps or the Shell in the end.
