### ISSUE TITLE
Collapsible Panel

### ISSUE THREAD

**Issue by nicolas2bert** [scality/core-ui#18]
https://github.com/scality/pensieve-front/blob/master/src/react/ui-elements/Collapsible.jsx

Collapsed:
<img width="938" alt="Screenshot 2019-10-08 at 09 50 30" src="https://user-images.githubusercontent.com/47394132/66377131-3ccc0e80-e9b1-11e9-8b3a-f67ed167973d.png">

Expanded:
<img width="944" alt="Screenshot 2019-10-08 at 09 50 39" src="https://user-images.githubusercontent.com/47394132/66377142-43f31c80-e9b1-11e9-9acf-eb8fc6a05e9a.png">

![image](https://user-images.githubusercontent.com/47394132/69791726-67726080-11c5-11ea-8291-0a2a0dc80f96.png)

```
type Props = {
  header: Node,
  onHeaderClick: any => void,
  expanded: boolean,
  children: Node, //content
};

```

**Comment by StheffanyHadlich** [comment]
Do you need help with this one? I can do it

**Comment by carlito-scality** [comment]
> Do you need help with this one? I can do it

Yes! Definitely :) If you have any questions, let me know. Thanks

**Comment by StheffanyHadlich** [comment]
@carlito-scality  is Node supposed to be the Header text?

**Comment by carlito-scality** [comment]
> @carlito-scality is Node supposed to be the Header text?

@StheffanyHadlich good question :) We would like to cover this case as well:
![image](https://user-images.githubusercontent.com/47394132/69791611-28dca600-11c5-11ea-9737-0ce6e910b3fc.png)

Consequently, we should allow users to put what they want in the header :)

**Comment by StheffanyHadlich** [comment]
:thinking: So maybe not a string, we could work with Node as an array and use flex to distribute its contents in Node container. What do you think?

**Comment by carlito-scality** [comment]
> 🤔 So maybe not a string, we could work with Node as an array and use flex to distribute its contents in Node container. What do you think?

Yes good idea. It could be an array of Node :)
