### ISSUE TITLE
Global Health Component enhancement

### ISSUE THREAD

**Issue by ChengYanJin** [scality/core-ui#186]
**Component**:
StatusBar

**Why this is needed**:
![image](https://user-images.githubusercontent.com/18453133/81296406-22a2fd80-9072-11ea-9701-c67ee838a31f.png)
Need to improve the UX and appearance of the whole StatusBar.

**What should be done**:

Two points need to be addressed as an enhancement:
1. Set cornerRadius for only one first&last rectangular.
2. Change the cursor to pointer when there is alert existed.
3. We are using hyperlink to redirect to the alert page. However, we would lose all the context. It's better to use the event handler.

> If you're using Vega-Embed, it returns a promise with a reference to the view which allows you to use addEventListener - explained in the docs here.
https://github.com/vega/vega-view#event-handling
```
const width = 600
const color = blue
embed(element, {
    $schema: 'https://vega.github.io/schema/vega-lite/3.0.0-rc6.json',
    data: { 'values': data },
    mark: {
        type: 'line',
        color,
        point: {
            color,
        }
    },
    width,
    height: width / 2,
    encoding: {
        'x': {
            field: 'label',
            type: 'temporal',
        },
        'y': {
            field: 'value',
            type: 'quantitative',
        },
    }
}).then(({spec, view}) => {
    view.addEventListener('mouseover', function (event, item) {
        console.log(item.datum)
    })
})
``` 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "width": 650,
  "height": 18,
  "data": {
    "values": [
      {
        "severity": "warning",
        "start": "2021-02-02T15:00:00Z",
        "end": "2021-02-03T00:00:00Z",
        "description": "Logging service"
      },
      {
        "severity": "critical",
        "start": "2021-02-03T00:00:00Z",
        "end": "2021-02-04T00:00:00Z",
         "description": "Logging service"
      },
      {
        "severity": "warning",
        "start": "2021-02-04T10:00:00Z",
        "end": "2021-02-06T00:00:00Z"
      },
      {
        "severity": "warning",
        "start": "2021-02-06T12:00:00Z",
        "end": "2021-02-06T20:00:00Z"
      }
    ]
  },
  "config": {
    "view": {
      "stroke": "transparent"
    }
  },
  "transform": [  {"calculate": "datum.description !== '' ? 'View details from alart page' : ''", "as": "title"} ],
  "layer": [
    {
      "mark": {"type": "rect", "cornerRadius": 15},
      "encoding": {"color": {"value": "#28a745"}}
    },
    {
      "mark": {"type": "rect", "cursor": "pointer"},
      "encoding": {
        "x": {
          "field": "start",
          "type": "temporal",
          "title": null,
          "stack": null,
          "scale": {
            "domain": [
              {"date": 1, "month": 2, "year": 2021},
              {"date": 7, "month": 2, "year": 2021}
            ]
          },
          "axis": {
            "format": "%d %b",
            "ticks": false,
            "grid": false,
            "domainWidth": 0,
            "tickCount": 7,
            "labelExpr": "[timeFormat(datum.value, '%d'), timeFormat(datum.value, '%d') == '01' ? timeFormat(datum.value, '%b') : '']",
            "labelColor": "#a8b5c1"
          }
        },
        "x2": {"field": "end"}
      }
    },
    {
      "mark": {
        "type": "rect",
        "tooltip": true,
        "cornerRadius": 0,
        "cursor": "pointer"
      },
      "params": [{"name":"highlight","select":{"type":"point","on":"mouseover"}}],
      "encoding": {
        "x": {
          "timeUnit": "yearmonthdatehoursminutes",
          "field": "start",
          "type": "temporal",
          "title": null,
          "axis": {
            "format": "%d %b",
            "labelExpr": "timeFormat(datum.value, '%H') == '00'? datum.label:''",
            "labelColor": "#a8b5c1"
          }
        },
        "x2": {"field": "end"},
        "color": {
          "field": "severity",
          "type": "nominal",
          "title": "null",
          "scale": {"range": ["#dc3545", "#fefa52"]},
          "legend": null
        },
        "tooltip": [
          {"field": "severity", "title": "Severity"},
          {"field": "start", "title": "Start", "type": "temporal","timeUnit": "yearmonthdatehoursminutes"},
          {"field": "end", "title": "End", "type": "temporal","timeUnit": "yearmonthdatehoursminutes"},
          {"field": "title", "title": "title"},
          {"field":"description","title": "Description"}
        ],
        "opacity": {
          "condition": {"param": "highlight", "value": 1},
          "value": 0.6
        }
      }
    }
  ]
}
```

Design update with tooltip:
![image](https://user-images.githubusercontent.com/18453133/112113975-c8daf180-8bb7-11eb-9447-fdc89bd3d061.png)

![image](https://user-images.githubusercontent.com/18453133/111979374-498ce580-8b05-11eb-8faf-ac3e7c2b1cef.png)

**Implementation proposal** (strongly recommended):
TBD

**Test plan**:
TBD

**Comment by JBWatenbergScality** [comment]
I'd like to purpose the following vega [spec](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAdxoATemgDsABh1L4NMljQAmMUrVJMKVKGJJBDOBDQBtUJjqC4aEAA4dAFIAAjYAMxCCNThiEisQmggQhgg4NUUQNNIAJzoATz9lJBzZGlkyTPDysjgcnDzZTD8ARkyIGxzm9FMdUxb+Pv5egBU9VHG9AC1MuFkMnr6BnQBmQZaxsVR+1BX-GYBfBU9vX3QAGTYyELSc4hooOETkhlkkBxpBJCYfdti6gpFEplCpVGp1BrlbogFbtTrQ3r9QZrPojFo6bYtXb+SgANhaKxmSjmCxAiOWKNMaNMmOxeIJh2OIC8mF+6AAInAAB7PFJvD5fH6+JTZAGYQroKB5LxQRxgioQxrQgAscJKCKWyMGVJaWx2e3phNm8z85K1qJaAE5aQb8UajidWWcAitQhEojE4sQ1Exeal0n9coD0MVSjV5bV6kq-KqRfDTZrVtq0XqsbaGcbSWakxbrfqcXbGY62QFTG7ItFYvEkH60hkRf9pRKVMDw0pqgqo1DTWqugmkTmNr0bQWM8STYsB5SRsP84ai8zTn4ANJwfJQQRsJAAaz9-KQn2+vwbQfFfildAecvb4K7TT8Yl7Gqn6zG-hH88z-Ypr5aNLnhYgA6i5On4-hiOWHpVt6vpJCkdaBmKzahiClQ3p2kL3uguJPt+5obDoWjbBi6ZGuOWaJiiGx-h+gEHAAukczI5EgsgQOEbA5Ag7igLKghQAwXyYM6mBsOy1hwAAFFYmAMAglAkgAlCE-AhKJ4nCdJ1hyZQHTqopmRIK46BqAwLFeHIQFMnxAlCc6Mk6aKTYhAAvG5IQAOQXjKjgeSEAD8ISmCEqAhG0ShGX4TkFOc-yCFZvGOLZElRXAACOziyI8WmyfJeldAoIQOfJJKFbieh6AZEXGSASBQF4pAALLlAwwmuMB4RCcJ8ioG4tX1TQTUtW1ICMUykhsOUSBkGQOR8MJPEgNUcCCKSHaRphzRKGwODnmwrxbbVNVQPtTQAII+F0EBnZgIwwEkzWyK1vgdTQK2ktF4qxaQ8Xbbt6DIFyhk1YDADKjYxXFN13Q9w0vfRSizftOBMBKfV1Q1cCPc9rhjaA02zfNZweEtb2rX462Kt2f1+GoSReFlh2RSZ9PlPVABit6bQlpPvX4GODVjcOuDT6AOE4LjA-zA1DU9I0MYjOTI6j7ggCdB0XXUmDXbd90QNjC3oRt0ZKCyx4gGDENfVDuuw3Lvh42rSWCSl6DqRJOU6QLss424Oj0ZQ3tC-bEBVUd-OXZgoPxsBNkuwtbtiR7OBwHA26e-JQcGy4imBzLwc42HzO1ZH0c7UBCMgF8+R1ItyA5NuaCePkKd+HN9WZCdpR1AASkgdOpGgupMXMJ106Cdhq2wm45E3IDi84fgAMSmP4SBaMqj4HNvTL143k-iq36Dt4dXeyL3-c0IPqC6nGSvbnAADq6iaDfd9sA-fg-HVjdKAJOQyFnugHAk0mi1xHllNg49KiTwlMWM4T1BCCDjD-NAmAcjOAilyJIaBEGCCYkDSey1yboHyodQ+IlEAgJYr9ECbI8EoKgPvBhWQ+JnFAGoNgyByiLRkmcFoSgEByFfisJQNcShmCWMBPhaBlSCOETANAoiQDiKAeSBiTEkDYOMqADiXFrB+CCGoEIQQmCZBlNuYy4RHBpEsFwg8shn4aEURMJQgoVoAFEuQND8F4BAcB2acWQJgDOlAF5wEKh5IIAAJDyyl3IeT0B5QKxVKDuMEKgDyHlMjpLOhUNk-BAhuO+CtAAwtPTiy8kD+CYGIKAbQd4gC5KYOexDSQkislPGerSyakktqefI30VrQz1tndobC54sQVKrJe4Q4DWLEC0pQS81BQBWGITeo0mIUL8LILhU1aE+FqBOPB2y2DTy8P9EmbS9oa0jjrGG+s4bmKXOgAAcnJJgdQwiREcFrdqjFgI4BKEgBAxkSZvH8X4YFUImAYIgIohsPgO4Hxbs6EB1MQCWQBvtNIbBchAQVhbEo+9m5HxACfOE98n4vxcQIrI6CP7Om-kwzuZlAHQtAcJWef9hD-XQc4CBY9wywLnmbBBglkEMtQagAVETaraNwZKghPS+boD+V0aO6pzFot8VQzi146ESqQYw5hkqRQTMnpw7hPUSYyLfhbBRSixFwAkcRfo0jXZyMdU0FxyjVGSI9WNBVOCiFBIMegIxJizGmweJYtA1jBC2JALNdQCabHyutQ4pxr99BVxKYILxPi3Y0H8YE-RITUnhMiTEuJrkXKeSSSk7S8l0mZOycUr5gg8lkAKUU-NXbyndPQEvaptT6mEqUM01VJCS5azLrtJiJ1h26N6X4fpSEhndttk8+24y-mTNYrUGZcyFlLJACstZGzHzBp2egPZCADmdI6NSnNLjeJyDphZHqoBgUsW4sAhxmA4WpERSAKhZ5UCJuTeEswTFYM3zORcmgVzV1qqnnc-5Iy7bPReaBd5nzvnug1drCu29K73DgMoOeZ8L4D2MsPP+chqgwNAB0fIbJeIrXipPF9TLfFTIgH+uYh0+MPzfWgHQ29t5AA) as a starting point to fix remaining issues :  

![image](https://user-images.githubusercontent.com/75977494/110362511-a5ee0080-8041-11eb-8d63-392460d9eb69.png)
