### ISSUE TITLE
Confirmation Popup

### ISSUE THREAD

**Issue by nicolas2bert** [scality/core-ui#19]
https://github.com/scality/pensieve-front/blob/master/src/react/ui-elements/ConfirmationPopup.jsx

<img width="324" alt="Screen Shot 2019-04-18 at 3 33 01 PM" src="https://user-images.githubusercontent.com/7453636/56395608-1bebe300-61f0-11e9-9a64-288b8885f710.png">

**Comment by carlito-scality** [comment]
It could be implemented by using the Modal https://github.com/scality/core-ui/tree/development/1.0/src/lib/components/modal
