### ISSUE TITLE
VegaChart component tries to render the graph even if the component has been unmounted leading to memory leak issues

### ISSUE THREAD

**Issue by JBWatenbergScality** [scality/core-ui#214]
**Component**:

VegaChart

**What happened**:

While quickly navigating in MetalK8s ui I noticed following error (among several similar others due to several instance of the component being rendered in the page) :

```
index.js:1 Error: #node_cpu_usage_id does not exist
    at _callee4$ (embed.ts:263)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at tslib.es6.js:74
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70)
    at _embed (embed.ts:251)
    at _callee$ (embed.ts:224)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at fulfilled (tslib.es6.js:71)
```

**What was expected**:

´VegaChart´ should handle the unmount of the component correctly and stop rendering of the chart if the component is unmounted.

**Steps to reproduce**

Run Metalk8s and quickly switch between ´Alerts´ and ´Metrics´ tab on nodes page.

**Resolution proposal** (optional):

We should add a cleanup function in this effect https://github.com/scality/core-ui/blob/development/1.0/src/lib/components/vegachart/VegaChart.component.js#L76 to interrupt vegaEmbed promise when the component is unmounted. However I didn't found a way to assign an abort controller or similar mechanism to vegaEmbed library to allow this so we might have to study another option maybe based on a ref to the element where we want vegaEmbed to actually render the graphs and in this way we would be able to abort the rendering in case of unmount.

**Comment by ChengYanJin** [comment]
Hello @JBWatenbergScality, 
Thanks for reporting the bug!

Would you think `view.finalize` from [vega-embed ](https://github.com/vega/vega-embed) can do the job?

**Comment by JBWatenbergScality** [comment]
Yes I think calling this method on cleanup function will definitely help but only solve half of the problem. Indeed if the component is unmounted before vega had the opportunity to be initialized then we will still have the issue.

I would probably go for something similar to this in a first approach :

```typescript
const vegaInstance = useRef<Result>();

  useEffect(() => {
      let isMounted = true;
      
      if (!vegaInstance.current) {
        vegaEmbed(`#${id}`, themedSpec, {
          renderer: "svg",
          tooltip: { theme: theme },
          // Determines if action links
          // ("Export as PNG/SVG", "View Source", "View Vega" (only for Vega-Lite), "Open in Vega Editor")
          // are included with the embedded view.
          // If the value is true, all action links will be shown and none if the value is false.
          actions: false,
        })
        .then(result => {
          vegaInstance.current = result;
        })
        .catch((...args) => {
          if (isMounted) {
            console.error(...args) // todo sould handle this with a retry or an error state of the component
          }
        });
      }
      
      return () => {
        isMounted = false;
        if (vegaInstance.current) {
          vegaInstance.current.view.finalize();
        }
      }
  }, [id, themedSpec, theme, vegaInstance]);
```

This could handle cleanup of Vega listener if it successfully had the opportunity to be initiailized and also ignore the issue of vega trying to render in a non existing dom element. I'm still not super happy with this solution because I would prefer found a way to interrupt vega promise in case of early unmount but as it might be a bit complex to implement I think it is a good trade off. What do you think ?
