### ISSUE TITLE
404 Not Found Page and 500 Error page

### ISSUE THREAD

**Issue by ChengYanJin** [scality/core-ui#245]
**Component**: UI

**Why this is needed**: 404 page and 500 page

**What should be done**:
Please check the latest design from Valamir (https://github.com/scality/core-ui/issues/245#issuecomment-802985316)

**Implementation proposal** (strongly recommended):
In both 404 page and 500 page: When clicking on the `Return Home` button should bring me to the `/` 

In 500 page:
We should have an optional prop for the `support link`. 
If the prop is not defined, we don't display "You may also contact support to report this issue."

**Test plan**:

**Comment by Cuervino** [comment]
Latest design. 
I removed the "documentation" icon.

404
<img width="1440" alt="error-404" src="https://user-images.githubusercontent.com/28654802/111817736-a9557780-88de-11eb-8e39-33a4409f063c.png">

500
<img width="1440" alt="error-500" src="https://user-images.githubusercontent.com/28654802/111817734-a8bce100-88de-11eb-98c2-edd4d055c906.png">
