### ISSUE TITLE
Update the padding with design multiple by 8px

### ISSUE THREAD

**Issue by ChengYanJin** [scality/core-ui#261]
**Component**: padding 

**Why this is needed**:
Current default padding in the core-ui is as below:
> export const padding = {
>   smaller: "5px",
>   small: "10px",
>   base: "15px",
>   large: "20px",
>   larger: "30px",
> };
> 

However, the paddings in the design system are 8px, 16px, 24px. 

**What should be done**:
Update the default paddings

**Implementation proposal** (strongly recommended):
@Cuervino would you agree with the following proposal?

> export const padding = {
>   smaller: "4px",
>   small: "8px",
>   base: "16px",
>   large: "20px",
>   larger: "24px",
> };

**Test plan**:
Tested by all the applications.

**Comment by Cuervino** [comment]
I do think that the proposed values make sense.
