### ISSUE TITLE
Add a border to the tooltip frame

### ISSUE THREAD

**Issue by Cuervino** [scality/core-ui#269]
**Component**:
Tooltip

**Why this is needed**:
When the tooltip is displayed, it's difficult to distinguish the tooltip from the background because they have very similar colors.
![image](https://user-images.githubusercontent.com/28654802/111187483-50bb6d00-85b4-11eb-900a-86f2f989267f.png)

**What should be done**:
Add a border to the tooltip - color 'border' (#313131)

**Implementation proposal** (strongly recommended):
![image](https://user-images.githubusercontent.com/28654802/111187963-d3dcc300-85b4-11eb-9141-90d89c4c11d8.png)

**Test plan**:

**Comment by theocerutti** [comment]
@ChengYanJin  Should there be the same border when changing the backgroundColor of the tooltip (by the overlayStyle props)?
