### ISSUE TITLE
restyle Notifications component

### ISSUE THREAD

**Issue by Cuervino** [scality/core-ui#271]
**Component**:
Notifications

**Why this is needed**:
The current design is a little bit too _colorful_, and not aligned with the look&feel of the other component.
![image](https://user-images.githubusercontent.com/28654802/111339355-fc79c100-8677-11eb-868e-8d051656c3c3.png)

**What should be done**:
Change the style of the notifications component.

**Implementation proposal** (strongly recommended):
<img width="718" alt="Alert Warning" src="https://user-images.githubusercontent.com/28654802/111339164-d6542100-8677-11eb-881e-bbd7c5e797c4.png">
Could/should be discussed.

Example with the progress bar.
<img width="718" alt="notification-proposal-with-progress" src="https://user-images.githubusercontent.com/28654802/111814225-84f79c00-88da-11eb-9697-61d78b72cb4e.png">

Example with icon and more than 1 line of text content.
<img width="718" alt="notification-proposal-with-icon" src="https://user-images.githubusercontent.com/28654802/111978798-a0de8600-8b04-11eb-9270-eb8c553b21ac.png">

**Test plan**:

**Comment by theocerutti** [comment]
1/ It looks like the future notification component is wider. Is it 10%, 25%, 50% the size of the screen?
2/ As there is no more background color (but only a border) the color of the close icon on HOVER seems weird (it was grayLightest). Should it be removed ?

**Comment by theocerutti** [comment]
@Cuervino
1/ It looks like the future notification component is wider. Is it 10%, 25%, 50% of the screen size?
2/ As there is no more background color (but only a border) the color of the close icon on HOVER seems weird (it was grayLightest). Should it be removed ?

**Comment by Cuervino** [comment]
1. The width of the notification component should follow the same rule as the previous/current component. It's not depending on the screen size.
2. We have an issue with the requirement and inspection. 
- There is indeed a background for this component. 
- The color will be updated with the new core-ui color update.
- Could you please check the inspection for this component here?
https://www.figma.com/file/wAUnQnUbUagSfH9oA8LugJ/notification?node-id=0%3A1

**Comment by theocerutti** [comment]
I made a branch with thoses changements. Should I make a PR now or wait for new core-ui colors ?

**Comment by theocerutti** [comment]
@Cuervino I made a branch with thoses changements. Should I make a PR now or wait for new core-ui colors ?

**Comment by Cuervino** [comment]
@theocerutti Let's wait for the new core-ui colors, please.

**Comment by Cuervino** [comment]
Let's hold it until we come back with a new "Error" and "Notification" system.

**Comment by Cuervino** [comment]
This has been done since this issue.
