### ISSUE TITLE
Scroll up automatically in Storybook Table component page

### ISSUE THREAD

**Issue by Cuervino** [scality/core-ui#282]
**Component**:
Table

**What happened**:
When displaying the table component, the scroll behavior becomes wild.
it starting at 10 items, then it's creating a total of 100 rows and slowly scrolling down.
Once the total of 100 rows is reached, the **table is scrolling up automatically**.

https://user-images.githubusercontent.com/28654802/112845149-d7884380-90a4-11eb-8e6d-0222cc4dce79.mp4

**What was expected**:
The scroll should be user-controlled, not automatic

**Steps to reproduce**
Only clicking on the Table component. 
Environment: Firefox or Chrome + Windows 

**Resolution proposal** (optional):

**Comment by ChengYanJin** [comment]
Hello @Cuervino 
This is the legacy table that we will remove completely once we extract the current table in different applications in core-ui.

So I will close it because we won't use and maintain this table anymore.
Thanks!
