### ISSUE TITLE
Update components with new colors

### ISSUE THREAD

**Issue by Cuervino** [scality/core-ui#302]
**Component**:

Buttons, Healthselector, Dropdown, Input, Searchinput, Breadcrumb, Modal, Tooltip, Loaders

**Why this is needed**:

New theme/colors

**What should be done**:

## Buttons
Here is the proposed design:
<img width="531" alt="button_core-ui" src="https://user-images.githubusercontent.com/28654802/114854323-fd238580-9de4-11eb-853e-1bb0179b1dc1.png">
The inspection will be done through Figma: https://www.figma.com/file/DjdwhMOMM7OK3xTcuD74O9/buttons?node-id=0%3A1

## Healthselector
- Set background-color: darkRebrand.buttonSecondary
![image](https://user-images.githubusercontent.com/28654802/114857567-b33c9e80-9de8-11eb-9261-6b6b95782311.png)

## Input and search Input
1. Set max Height of 32 px for being aligned with default button height. (Currently, it's 34px, or even more)
2. Set background-color: darkRebrand.backgroundLevel1

## Breadcrumb
1. The current level font color to set to darkRebrand.textPrimary
2. Previous levels with link to set to textLink. On hover, the link color should be set to darkRebrand.selectedActive.
<img width="298" alt="breadcrumb" src="https://user-images.githubusercontent.com/28654802/114869585-71ffbb00-9df7-11eb-9a71-1e027bb361d1.png">

## Modal
1. Main mode bg color to set to backgroundLevel1_rb_121219
2. Bottom-modal color to set to backgroundLevel4_rb_171721  
![image](https://user-images.githubusercontent.com/28654802/114901212-de3ce780-9e14-11eb-83ea-d7447cdc7118.png)

3. The buttons in modals should be the default size ones (currently the font-size: 12px and the height is 30px; font should be 14px and 32px high)

## Tooltip
- Set background-color: darkRebrand.backgroundLevel1
- (keep the border)

## Loaders
- PROPOSAL: Set background-color: Set background-color: #A14FBF (outside of any theme for the moment)
![image](https://user-images.githubusercontent.com/28654802/114857373-783a6b00-9de8-11eb-95e2-6dfcb514d62c.png)

## Table
I don't think we are directly using them.

## Dropdown and Select
It's not clear what is already selected, disabled, possible to select + the cursor should be action, not remain the same

**Comment by ChengYanJin** [comment]
Hello @Cuervino, can you please add the new branding of `navbar`, `sidebar` and `tabs` as well?  thank you!
