### ISSUE TITLE
Component: Chips

### ISSUE THREAD

**Issue by carlito-scality** [scality/core-ui#82]
**Component**:Chips

**Why this is needed**:
- We need this component to display in the filters bar ou Select component (https://github.com/JedWatson/react-select/issues/1263)
![image](https://user-images.githubusercontent.com/47394132/65040047-d7f23b00-d953-11e9-855a-cfd9db2acffd.png)

**What should be done**:

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by StheffanyHadlich** [comment]
I can work on this one

**Comment by carlito-scality** [comment]
> I can work on this one

Hello! It would be great :)
Please follow these guidelines https://github.com/scality/core-ui#how-to-contribute Thanks
